services:
  - type: web
    name: ecommerce-store
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: e-commerce-store-2bqi.onrender.com

